export const EXPENSE_ADDED_BY_OPTIONS = ["YASSAR", "ALEX"];

export const DEFAULT_CATEGORIES = [
  { name: "House Rent", type: "income" },
  { name: "Salary", type: "income" },
  { name: "Shop", type: "income" },
  { name: "Extra", type: "income" },
  { name: "Beverage", type: "expense" },
  { name: "Shop Rent", type: "expense" },
  { name: "Home Rent", type: "expense" },
  { name: "Talabat", type: "expense" },
  { name: "Taxi", type: "expense" },
  { name: "Salik", type: "expense" },
  { name: "Shop Supply", type: "expense" },
  { name: "School", type: "expense" },
  { name: "Alex", type: "expense" },
  { name: "Yassar", type: "expense" },
  { name: "Barber", type: "expense" },
  { name: "VAT", type: "expense" },
  { name: "Cloth", type: "expense" },
  { name: "Kids Gifts", type: "expense" },
  { name: "DEWA", type: "expense" },
  { name: "DU", type: "expense" },
  { name: "Etisalat Shop", type: "expense" },
  { name: "Etisalat Yassar", type: "expense" },
  { name: "Internet Home", type: "expense" },
  { name: "EMPOWER", type: "expense" },
  { name: "Overtime", type: "expense" },
  { name: "Gov Fees", type: "expense" },
  { name: "Food", type: "expense" },
  { name: "Going Out", type: "expense" },
  { name: "Doctor", type: "expense" },
  { name: "Fuel Alex", type: "expense" },
  { name: "Fuel Yassar", type: "expense" },
  { name: "Car Repair", type: "expense" },
  { name: "Car Loan", type: "expense" },
  { name: "TSB Loan", type: "expense" },
];

export const REPORT_RANGE_OPTIONS = [
  { key: "today", label: "Today" },
  { key: "week", label: "Last 7 days" },
  { key: "month", label: "This month" },
  { key: "all", label: "All time" },
];
